version: '3.8'
services:
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=mightyblade
      - POSTGRES_PASSWORD=mightyblade
      - POSTGRES_DB=mightyblade
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local