// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ItemHandler is an autogenerated mock type for the ItemHandler type
type ItemHandler struct {
	mock.Mock
}

// Route provides a mock function with given fields: r
func (_m *ItemHandler) Route(r *gin.Engine) {
	_m.Called(r)
}

// NewItemHandler creates a new instance of ItemHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemHandler {
	mock := &ItemHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
